# Generated by Django 5.1.5 on 2025-01-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_project', '0002_delete_timepass_remove_client_user_client_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='clients_project.project'),
        ),
    ]
